In [1]:
d = 9*2
d

18

In [27]:
import numpy as np
C = [[18.63964745, 12.20609082],
       [12.20609082, 19.35245652]]
C

[[18.63964745, 12.20609082], [12.20609082, 19.35245652]]

In [28]:
 eigvals, eigvecs = np.linalg.eig(C)
eigvals, eigvecs

(array([ 6.78475896, 31.20734501]), array([[-0.71735154, -0.69671139],
        [ 0.69671139, -0.71735154]]))

In [29]:
eigvecs

array([[-0.71735154, -0.69671139],
       [ 0.69671139, -0.71735154]])

In [30]:
eigvecs[0]

array([-0.71735154, -0.69671139])

In [31]:
eigvecs[1]

array([ 0.69671139, -0.71735154])

In [32]:
eigvals

array([ 6.78475896, 31.20734501])

In [33]:
eigvals[0]

6.784758961791654

In [34]:
x = np.dot(eigvecs[0],eigvals[0] )
x

array([-4.8670573 , -4.72701887])

In [35]:
y = np.dot(eigvecs[1],eigvals[1] )
y

array([ 21.74251281, -22.38663707])

In [38]:
Z = np.dot(C, eigvecs[0] )
Z

array([-21.87530238, -22.23913501])

In [39]:
Z = np.dot(C, eigvecs[1] )
Z

array([ 4.23039667, -5.37839199])